const tools=[
["🔤","Word Counter","Count words, characters, sentences and paragraphs.",wordCounter],
["🔠","Text Case Converter","Convert text to upper, lower, title and sentence case.",caseConverter],
["🎂","Age Calculator","Calculate age from a birth date.",ageCalculator],
["％","Percentage Calculator","Find a percentage of a number.",percentageCalculator],
["▣","QR Code Generator","Create a QR code from text or a URL.",qrGenerator],
["🔐","Password Generator","Generate a random password in your browser.",passwordGenerator],
["📏","Unit Converter","Convert length between meters, centimeters and feet.",unitConverter],
["🧮","Average Calculator","Calculate the average of a list of numbers.",averageCalculator],
["🔢","Number Formatter","Format numbers with readable separators.",numberFormatter],
["📝","Text Cleaner","Remove extra spaces and clean line breaks.",textCleaner],
["🔄","JSON Formatter","Validate and pretty-print JSON.",jsonFormatter],
["🔗","URL Encoder","Encode text safely for use in URLs.",urlEncoder],
["📅","Days Between Dates","Calculate the number of days between two dates.",daysBetween],
["🎯","Tip Calculator","Calculate a tip and total amount.",tipCalculator],
["🌡️","Temperature Converter","Convert Celsius to Fahrenheit and Kelvin.",temperatureConverter],
["📐","Square Calculator","Calculate square area and perimeter.",squareCalculator],
["⏱️","Countdown Timer","Run a simple browser countdown timer.",countdownTimer],
["🧾","Invoice Helper","Calculate subtotal, tax and total.",invoiceHelper],
["🖼️","Image Resizer","Resize an image in your browser and download it.",imageResizer],
["🎲","Random Number Generator","Generate a random integer in a range.",randomNumber]
];
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),count=document.querySelector('#count');
function openTool(title,html,setup){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><button class="close" aria-label="Close">×</button><h2>${title}</h2><div class="tool-ui">${html}</div></div>`;document.body.appendChild(modal);modal.querySelector('.close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});if(setup)setup(modal)}
function wordCounter(){openTool('Word Counter','<textarea id="tc" rows="8" placeholder="Paste or type text..."></textarea><div class="stats"><span id="w">0 words</span><span id="ch">0 characters</span><span id="sc">0 sentences</span><span id="pc">0 paragraphs</span></div>',m=>{const t=m.querySelector('#tc');const update=()=>{const v=t.value;const words=v.trim()?v.trim().split(/\s+/).length:0;const sentences=v.trim()?(v.match(/[.!?]+(?=\s|$)/g)||[]).length:0;const paragraphs=v.trim()?v.split(/\n\s*\n/).filter(Boolean).length:0;m.querySelector('#w').textContent=words+' words';m.querySelector('#ch').textContent=v.length+' characters';m.querySelector('#sc').textContent=sentences+' sentences';m.querySelector('#pc').textContent=paragraphs+' paragraphs'};t.oninput=update})}
function caseConverter(){openTool('Text Case Converter','<textarea id="caseText" rows="8" placeholder="Enter text..."></textarea><div class="button-row"><button data-c="upper">UPPERCASE</button><button data-c="lower">lowercase</button><button data-c="title">Title Case</button><button data-c="sentence">Sentence case</button></div>',m=>{const t=m.querySelector('#caseText');m.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const v=t.value;b.dataset.c==='upper'?t.value=v.toUpperCase():b.dataset.c==='lower'?t.value=v.toLowerCase():b.dataset.c==='title'?t.value=v.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):t.value=v.toLowerCase().replace(/(^|[.!?]\s+)(\w)/g,(a,p,c)=>p+c.toUpperCase())})})}
function ageCalculator(){openTool('Age Calculator','<label>Birth date<input id="birth" type="date"></label><button id="calc">Calculate age</button><div id="result" class="result"></div>',m=>{m.querySelector('#calc').onclick=()=>{const d=new Date(m.querySelector('#birth').value+'T00:00:00');if(isNaN(d)){m.querySelector('#result').textContent='Please choose a valid date.';return}const n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;m.querySelector('#result').textContent=a>=0?'Age: '+a+' years':'Please choose a valid past date.'}})}
function percentageCalculator(){openTool('Percentage Calculator','<label>Percentage<input id="p" type="number" step="any"></label><label>Number<input id="n" type="number" step="any"></label><button id="go">Calculate</button><div id="r" class="result"></div>',m=>m.querySelector('#go').onclick=()=>{const p=+m.querySelector('#p').value,n=+m.querySelector('#n').value;m.querySelector('#r').textContent=`${p}% of ${n} = ${(p*n/100).toLocaleString()}`})}
function qrGenerator(){openTool('QR Code Generator','<input id="qrText" placeholder="Enter text or URL"><button id="make">Generate QR</button><div id="qrResult"></div><small>QR generation uses a third-party image service. Do not enter passwords or sensitive information.</small>',m=>m.querySelector('#make').onclick=()=>{const v=m.querySelector('#qrText').value.trim();if(!v)return;m.querySelector('#qrResult').innerHTML=`<img class="qr" alt="Generated QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(v)}"><p><a target="_blank" rel="noopener" href="https://api.qrserver.com/v1/create-qr-code/?size=600x600&data=${encodeURIComponent(v)}">Open larger image</a></p>`})}
function passwordGenerator(){openTool('Password Generator','<label>Length<input id="len" type="number" min="6" max="64" value="16"></label><button id="gen">Generate</button><input id="pass" readonly><button id="copy">Copy</button>',m=>{const make=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*';let s='';const l=Math.min(64,Math.max(6,+m.querySelector('#len').value||16));for(let i=0;i<l;i++)s+=chars[Math.floor(Math.random()*chars.length)];m.querySelector('#pass').value=s};m.querySelector('#gen').onclick=make;m.querySelector('#copy').onclick=()=>navigator.clipboard?.writeText(m.querySelector('#pass').value);make()})}
function unitConverter(){openTool('Unit Converter','<label>Meters<input id="m" type="number" step="any"></label><button id="conv">Convert</button><div id="u" class="result"></div>',m=>m.querySelector('#conv').onclick=()=>{const v=+m.querySelector('#m').value;m.querySelector('#u').innerHTML=`${v} m = ${(v*100).toFixed(2)} cm<br>${v} m = ${(v*3.28084).toFixed(3)} ft<br>${v} m = ${(v*39.3701).toFixed(2)} in`})}
function averageCalculator(){openTool('Average Calculator','<textarea id="nums" rows="5" placeholder="10, 20, 30"></textarea><button id="avg">Calculate average</button><div id="a" class="result"></div>',m=>m.querySelector('#avg').onclick=()=>{const x=m.querySelector('#nums').value.split(/[,\s]+/).map(Number).filter(Number.isFinite);m.querySelector('#a').textContent=x.length?'Average: '+(x.reduce((a,b)=>a+b,0)/x.length).toLocaleString():'Enter numbers.'})}
function numberFormatter(){openTool('Number Formatter','<input id="num" type="text" placeholder="1234567.89"><button id="fmt">Format</button><div id="f" class="result"></div>',m=>m.querySelector('#fmt').onclick=()=>{const n=Number(m.querySelector('#num').value.replace(/,/g,''));m.querySelector('#f').textContent=Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:20}):'Enter a valid number.'})}
function textCleaner(){openTool('Text Cleaner','<textarea id="clean" rows="8" placeholder="Paste text..."></textarea><button id="cleanBtn">Clean text</button>',m=>m.querySelector('#cleanBtn').onclick=()=>{const t=m.querySelector('#clean');t.value=t.value.replace(/[ \t]+/g,' ').split('\n').map(x=>x.trim()).filter((x,i,a)=>x||a[i-1]).join('\n').trim()})}
function jsonFormatter(){openTool('JSON Formatter','<textarea id="json" rows="10" placeholder="Paste JSON..."></textarea><button id="pretty">Format JSON</button><div id="jr" class="result"></div>',m=>m.querySelector('#pretty').onclick=()=>{try{const o=JSON.parse(m.querySelector('#json').value);m.querySelector('#json').value=JSON.stringify(o,null,2);m.querySelector('#jr').textContent='Valid JSON ✓'}catch(e){m.querySelector('#jr').textContent='Invalid JSON — please check commas, quotes and brackets.'}})}
function urlEncoder(){openTool('URL Encoder','<textarea id="url" rows="5" placeholder="Text to encode..."></textarea><button id="enc">Encode</button><div id="er" class="result"></div>',m=>m.querySelector('#enc').onclick=()=>m.querySelector('#er').textContent=encodeURIComponent(m.querySelector('#url').value))}
function daysBetween(){openTool('Days Between Dates','<label>First date<input id="d1" type="date"></label><label>Second date<input id="d2" type="date"></label><button id="days">Calculate</button><div id="dr" class="result"></div>',m=>m.querySelector('#days').onclick=()=>{const a=new Date(m.querySelector('#d1').value+'T00:00:00'),b=new Date(m.querySelector('#d2').value+'T00:00:00');if(isNaN(a)||isNaN(b)){m.querySelector('#dr').textContent='Choose both dates.';return}m.querySelector('#dr').textContent=Math.abs(Math.round((b-a)/86400000))+' days'}})}
function tipCalculator(){openTool('Tip Calculator','<label>Bill<input id="bill" type="number" step="any"></label><label>Tip %<input id="tip" type="number" step="any" value="10"></label><button id="tipgo">Calculate</button><div id="tr" class="result"></div>',m=>m.querySelector('#tipgo').onclick=()=>{const b=+m.querySelector('#bill').value,p=+m.querySelector('#tip').value;m.querySelector('#tr').innerHTML=`Tip: ${(b*p/100).toFixed(2)}<br>Total: ${(b+b*p/100).toFixed(2)}`})}
function temperatureConverter(){openTool('Temperature Converter','<label>Celsius<input id="c" type="number" step="any"></label><button id="temp">Convert</button><div id="tempR" class="result"></div>',m=>m.querySelector('#temp').onclick=()=>{const c=+m.querySelector('#c').value;m.querySelector('#tempR').innerHTML=`Fahrenheit: ${(c*9/5+32).toFixed(2)}°F<br>Kelvin: ${(c+273.15).toFixed(2)} K`})}
function squareCalculator(){openTool('Square Calculator','<label>Side length<input id="side" type="number" min="0" step="any"></label><button id="sq">Calculate</button><div id="sqr" class="result"></div>',m=>m.querySelector('#sq').onclick=()=>{const s=+m.querySelector('#side').value;m.querySelector('#sqr').innerHTML=`Area: ${(s*s).toLocaleString()}<br>Perimeter: ${(s*4).toLocaleString()}`})}
function countdownTimer(){openTool('Countdown Timer','<div class="timer" id="timer">00:00</div><div class="timer-row"><input id="mins" type="number" min="0" value="1"><button id="start">Start</button><button id="stop">Stop</button><button id="reset">Reset</button></div>',m=>{let timer=null,total=60;const out=m.querySelector('#timer');const draw=()=>out.textContent=String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0');m.querySelector('#start').onclick=()=>{if(timer)return;total=Math.max(0,+m.querySelector('#mins').value*60);draw();timer=setInterval(()=>{total--;draw();if(total<=0){clearInterval(timer);timer=null;alert('Time is up.')}},1000)};m.querySelector('#stop').onclick=()=>{clearInterval(timer);timer=null};m.querySelector('#reset').onclick=()=>{clearInterval(timer);timer=null;total=0;draw()};draw()})}
function invoiceHelper(){openTool('Invoice Helper','<label>Subtotal<input id="sub" type="number" step="any"></label><label>Tax %<input id="tax" type="number" step="any" value="0"></label><button id="inv">Calculate</button><div id="ir" class="result"></div>',m=>m.querySelector('#inv').onclick=()=>{const s=+m.querySelector('#sub').value,t=+m.querySelector('#tax').value;const tax=s*t/100;m.querySelector('#ir').innerHTML=`Tax: ${tax.toFixed(2)}<br>Total: ${(s+tax).toFixed(2)}`})}
function imageResizer(){openTool('Image Resizer','<input id="img" type="file" accept="image/*"><div id="imgUI"></div>',m=>m.querySelector('#img').onchange=e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);const im=new Image();im.onload=()=>{m.querySelector('#imgUI').innerHTML=`<p>Original: ${im.width} × ${im.height}px</p><label>Width<input id="iw" type="number" value="${im.width}"></label><label>Height<input id="ih" type="number" value="${im.height}"></label><button id="resize">Resize & Download</button>`;m.querySelector('#resize').onclick=()=>{const w=+m.querySelector('#iw').value,h=+m.querySelector('#ih').value;if(!w||!h)return;const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='toolnest-resized-image.png';a.click()},'image/png')}};im.src=url})}
function randomNumber(){openTool('Random Number Generator','<label>Minimum<input id="min" type="number" value="1"></label><label>Maximum<input id="max" type="number" value="100"></label><button id="rand">Generate</button><div id="rr" class="result"></div>',m=>m.querySelector('#rand').onclick=()=>{let a=+m.querySelector('#min').value,b=+m.querySelector('#max').value;if(a>b)[a,b]=[b,a];m.querySelector('#rr').textContent='Random number: '+Math.floor(Math.random()*(b-a+1)+a)})}
function render(q=''){grid.innerHTML='';const f=tools.filter(x=>(x[1]+' '+x[2]).toLowerCase().includes(q.toLowerCase()));count.textContent=f.length+' tools';f.forEach(x=>{const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><button>Open tool</button>`;c.querySelector('button').onclick=x[3];grid.appendChild(c)})}
search.oninput=()=>render(search.value);render();document.querySelector('#year').textContent=new Date().getFullYear();
